[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Anki Translation Guide"

[build]
create-missing = true

[output.html]
#no-section-label = true
git-repository-url = "https://github.com/ankitects/translating"
additional-css = ["custom.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true


[output.html.redirect]
"/index.html" = "https://docs.ankiweb.net/translators/intro"
"/intro.html" = "https://docs.ankiweb.net/translators/intro" 
"/ankidroid.html" = "https://docs.ankiweb.net/translators/ankidroid" 
"/ankimobile.html" = "https://docs.ankiweb.net/translators/ankimobile" 
"/anki/index.html" = "https://docs.ankiweb.net/translators/anki/intro"
"/anki/core.html" = "https://docs.ankiweb.net/translators/anki/core" 
"/anki/desktop.html" = "https://docs.ankiweb.net/translators/anki/desktop" 
"/anki/intro.html" = "https://docs.ankiweb.net/translators/anki/intro" 
"/anki/manual.html" = "https://docs.ankiweb.net/translators/anki/manual" 
"/anki/developers.html" = "https://docs.ankiweb.net/translators/anki/developers" 

